version: "3.8"

services:
    web:
        build: 
            context: .
        volumes: 
            - static_data:/vol/web
        environment: 
            - SECRET_KEY=key
            - ALLOWED_HOSTS=127.0.0.1,localhost
            - DEBUG=0
        depends_on: 
            - db
    proxy:
        build:
            context: ./proxy
        volumes: 
            - static_data:/vol/static
        ports: 
            - "8080:8080"
        depends_on: 
            - web
    db:
        image: postgres
        environment: 
            - TZ=Asia/Kolkata
            - PGTZ=Asia/Kolkata
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGUSER=postgres

volumes: 
    static_data:


